### ISSUE TITLE
Disambiguate the use of `ml-aoi:role` and Asset `roles`

### ISSUE THREAD

**Issue by fmigneault** [stac-extensions/ml-aoi#10]
When using `ml-aoi:role` under a Link using `rel: derived_from` (see https://github.com/stac-extensions/ml-aoi?tab=readme-ov-file#links), the specific ML-AOI role makes sense as there is no "role" otherwise provided. However, using `ml-aoi:role` under an Asset seems somewhat redundant, since Assets already contains a `roles` property. The `ml-aoi:role` under an Asset remains valid to be more specific than the `properties` at the STAC Item level (which would apply to all underlying Assets), but the specific use of the term "role" can lead to confusion. 

Should there be some additional requirements that add define additional ML-AOI specific roles under the Asset Roles directly? Would that cause even more confusion? Is the solution just to modify the term "role" globally?

For example: 
```yaml
assets:
  label:
    ml-aoi:role: label  # this to be removed?
    roles: 
      - ml-aoi:label  # or simply "label"?
      - data
  raster:
    ml-aoi:role: feature # this to be removed?
    roles: 
      - ml-aoi:feature # or simply "feature"?
      - data
      - source
```
